### ISSUE TITLE
 Requiring module "node_modules\react-native-make-it-rain\src\index.js"

### ISSUE THREAD

**Issue by parsbarghandan** [peacechen/react-native-make-it-rain#14]
Hi,
I want to add this package to Success.jsx file. However, when I import that package I receive this error.
`Error: Requiring module "node_modules\react-native-make-it-rain\src\index.js", which threw an exception: TypeError: _ReanimatedModule.default.configureProps is not a function. (In '_ReanimatedModule.default.configureProps(Object.keys(NATIVE_THREAD_PROPS_WHITELIST), Object.keys(UI_THREAD_PROPS_WHITELIST))', '_ReanimatedModule.default.configureProps' is undefined)`

When I remove the package from the file, my code works.
Is there any way to fix the error ?

**Comment by peacechen** [comment]
Which version of react-native-reanimated is in your app? The one specified in this library is 1.8.0.

**Comment by parsbarghandan** [comment]
> Which version of react-native-reanimated is in your app? The one specified in this library is 1.8.0.

Thanks for your kind response.
I'm currently using `"react-native-reanimated": "~2.9.1",`.
Should I have to install 1.8.0. version in order to use the package ?

**Comment by peacechen** [comment]
Did a different version of reanimated fix your issue?
There's an open PR to update it to 2.8.0 if you'd like to try out that version

**Comment by parsbarghandan** [comment]
Hi,
Yes, the issue is fixed,
Thanks a lot

**Comment by peacechen** [comment]
Thanks for the update. Would you mind listing the versions that work and doesn't work?
2.9.1 : fails?
2.8.0 : works?

**Comment by parsbarghandan** [comment]
Hi,
2.9.1 => 👎 
2.8.1 => 👍
